3 task
harshedabdulla/bloggy pull request #6
Opened 2024-06-18 11:36 UTC by harshedabdulla

closes #5

2024-06-18 15:25 UTC, mohitrajane commented
@harshedabdulla make sure that if the user is not logged in and in `/posts`, the user should be redirected to `/login`

2024-06-19 09:38 UTC, mohitrajane requested changes

2024-06-19 09:38 UTC, mohitrajane commented on src/bloggy_backend/main.mo
> +
please remove these unrequired comments

2024-06-19 09:38 UTC, mohitrajane commented on src/bloggy_backend/main.mo
>    var nextId: Nat = 0;
will nextId be reset to 0 each time the contract is deployed?

2024-06-19 09:38 UTC, mohitrajane commented on src/bloggy_frontend/src/pages/UserLogin.jsx
> +      }
This can be done using CSS. https://www.sitepoint.com/css-typewriter-effect/

2024-06-19 15:09 UTC, harshedabdulla commented on src/bloggy_backend/main.mo
>    var nextId: Nat = 0;
No, nextId will not be reset to 0 each time the contract is deployed, as the upgrade process preserves its value using preupgrade and postupgrade functions.

2024-06-20 08:39 UTC, merged